name: dab
#description: A client for your git repo hosting.
# version: 1.0.0
# homepage: https://www.example.com
# author: mockturtl <mockturtl@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dotenv: ^1.0.0
  http: ^0.11.3
  json_annotation: ^2.0.0
  path: ^1.6.2
  pub_semver: ^1.4.2
  pubspec_parse: ^0.1.4
  yamlicious: ^0.1.0

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  pubspec_parse:
    path: ../pubspec_parse

executables:
  dab: