name: dab
description: The dart+pub companion.  ヽ( •_)ᕗ
version: 1.0.0
author: mockturtl <mockturtl@gmail.com>
homepage: https://pub.dev/packages/dab

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  build_cli_annotations: ^1.1.0
  http: ^0.11.3
  json_annotation: ^2.0.0
  pub_semver: ^1.4.2
  pubspec_parse: ^0.1.4

dev_dependencies:
  build_cli: ^1.3.2
  build_runner: ^1.2.8
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
