name: dab
description: A client for your git repo hosting.
# version: 1.0.0
# homepage: https://www.example.com
# author: mockturtl <mockturtl@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dotenv: ^1.0.0
  http: ^0.11.3

dev_dependencies:
  test: ^1.0.0
